### ISSUE TITLE
 java.lang.NoClassDefFoundError: jline/ConsoleRunner on "cljr repl"

### ISSUE THREAD

**Issue by sritchie** [liebke/cljr#20]
I saw that this used to be an issue for Cygwin -- I'm getting it now on OS X Snow Leopard. Very odd!

Steps used to install -- 
1) Download cljr-installer.jar from http://incanter.org/downloads/cljr-installer.jar
2) run with java -jar cljr-installer
3) navigate to ~/.cljr/bin, run ./cljr repl -- error occurs

`cljr list` works fine... `cljr swank` causes

```
Caused by: java.lang.ClassNotFoundException: cljr.App
```

Oh, after some playing around, I can note that `cljr clean` followed by `cljr reload` fixes this issue.

**Comment by anteAdamovic** [comment]
Having the same issue, `cljr clean && cljr reload` didn't fix it for me

```
Exception in thread "main" java.lang.NoClassDefFoundError: clojure/lang/RT
        at cljr.App.main(App.java:11)
Caused by: java.lang.ClassNotFoundException: clojure.lang.RT
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more
```

when running `cljr repl` or `cljr swingrepl`.
