### ISSUE TITLE
install failures -- No method in multimethod 'do-copy' for dispatch value: [nil java.io.File]

### ISSUE THREAD

**Issue by foogoof** [liebke/cljr#3]
(OT: Github puts a .zip extension when downloading the jar file with Chrome on MacOSX)

Two stacktraces. The first happened on the first install attempt and the second happens on each subsequent attempt. Timestamp is 2010-06-26 06:45 EST

% java -jar clj-1.0.0-SNAPSHOT-standalone.jar.zip self-install
java -jar clj-1.0.0-SNAPSHOT-standalone.jar.zip self-install
/Users/seths/.clj / project.clj does not exist, clj must be initialized.
## The  /Users/seths/.clj/lib/  repository does not exist, needs to be initialized.

Initializing clj...
Creating clj home,  /Users/seths/.clj ...
Copying  to /Users/seths/.clj/clj.jar...
Exception in thread "main" java.lang.IllegalArgumentException: No method in multimethod 'do-copy' for dispatch value: [nil java.io.File]
    at clojure.lang.MultiFn.getFn(MultiFn.java:121)
    at clojure.lang.MultiFn.invoke(MultiFn.java:171)
    at clojure.java.io$copy.doInvoke(io.clj:383)
    at clojure.lang.RestFn.invoke(RestFn.java:426)
    at clj.main$clj_self_install.invoke(main.clj:243)
    at clj.main$clj.doInvoke(main.clj:420)
    at clojure.lang.RestFn.invoke(RestFn.java:411)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.RestFn.applyTo(RestFn.java:133)
    at clojure.core$apply.invoke(core.clj:540)
    at clj.main$_main.doInvoke(main.clj:443)
    at clojure.lang.RestFn.applyTo(RestFn.java:138)
    at clj.main.main(Unknown Source)
# 

% java -jar clj-1.0.0-SNAPSHOT-standalone.jar self-install
java -jar clj-1.0.0-SNAPSHOT-standalone.jar self-install
/Users/seths/.clj / project.clj does not exist, clj must be initialized.
Exception in thread "main" java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.net.URL;
    at clj.main$add_clj_repo_to_classpath.invoke(main.clj:214)
    at clj.main$add_clj_repo_to_classpath.invoke(main.clj:201)
    at clj.main$clj.doInvoke(main.clj:417)
    at clojure.lang.RestFn.invoke(RestFn.java:411)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.RestFn.applyTo(RestFn.java:133)
    at clojure.core$apply.invoke(core.clj:540)
    at clj.main$_main.doInvoke(main.clj:443)
    at clojure.lang.RestFn.applyTo(RestFn.java:138)
    at clj.main.main(Unknown Source)

**Comment by foogoof** [comment]
Suddenly I can't reproduce this. I cleared out ~/.clj and now self-install works fine. Not sure what happened.

**Comment by liebke** [comment]
Seth, the self-install task would not work if the clj jar file had a zip extension, but I have fixed that now.
